update Unet3d
pytorch-tpu/training pull request #4
Opened 2023-02-24 02:13 UTC by suexu1025

- add unet3d support for brats data
- fix data loading slow on gsc using long file path
- add run_brats/run_kitts scripts

2023-02-24 18:50 UTC, JackCaoG commented
I don't have enough context to review the full pr, @miladm Do you want to give it a try?

2023-02-28 00:24 UTC, miladm requested changes
Thanks for the PR @suexu1025 

Left a few questions and comments here.

We need to outline the perf gains w/ and w/o Brats in this PR. Feel free to make a separate PR for Brats if more convenient - your call.

2023-02-28 00:24 UTC, miladm commented on image_segmentation/pytorch/main.py
> +    if flags.use_brats:
I'd say we can have Brats as a use-case example. To given the state of Unet3D in MLPerf, it makes sense to keep Brats as an optional choice.

This means your PR focuses on Unet3D general optimizations, and enables those interested in Brats to give it a try.

2023-02-28 00:24 UTC, miladm commented on image_segmentation/pytorch/main.py
> +    # to match original paper, but still high variance
do you need these comments to stay?

2023-02-28 00:24 UTC, miladm commented on image_segmentation/pytorch/model/losses.py
> +        prediction_sum = torch.sum(prediction, dim=reduce_axis).float()
why do you need this `float()` conversion?

2023-02-28 00:24 UTC, miladm commented on image_segmentation/pytorch/runtime/inference.py
> +            #with autocast(enabled=flags.amp):
do we not need amp `autocast`? if not, do you plan to drop this line?

2023-02-28 00:24 UTC, miladm commented on image_segmentation/pytorch/runtime/trainer/unet3d_trainer.py
> +                            global_step=epoch * 10000 // 64 + iteration,
do you need to keep these numbers hard-coded?

2023-02-28 00:24 UTC, miladm commented on image_segmentation/pytorch/runtime/trainer/xla_trainer.py
> +            # test_utils.write_to_summary(
do you need these commented lines?

2023-02-28 21:52 UTC, suexu1025 commented on image_segmentation/pytorch/main.py
> +    if flags.use_brats:
sg, will keep brats as optional.

2023-03-01 22:11 UTC, suexu1025 commented on image_segmentation/pytorch/runtime/inference.py
> +            #with autocast(enabled=flags.amp):
restored

2023-03-02 18:15 UTC, suexu1025 commented
# address PR comment and summary of the PR benchmark result.

UNET3D @ BRATS with BS 64 convergent at mean epoch of  63.7 with std 9.2 @0.845 DICE
UNET3D @ KITS with BS 56 convergent at mean epoch of  2213.4 with std 499.9. @0.908 DICE
e2e training time of BRATS vs KITS ~ 1:4

general performance from this PR:
on v4-8 expected throughputs of 17.8 samples/s on GCS.
Improvement over original impl: 28% using disk, 48% using GCS
on v4-128 expected throughputs of 263.2 samples/s on GCS 
Improvement over original impl: 2.7x using disk 6.4x using GCS.

2023-09-08 21:20 UTC, merged